Fix blogs & create admin
markoding-platform/markodingplatform-api pull request #27
Opened 2021-01-02 01:53 UTC by yofriadi

review please @akbarsahata @ibnuimam @azhariemuhammad thankyou

disini ada yang gue pakein `@ts-ignore` engga tau kenapa errornya

2021-01-02 01:58 UTC, azhariemuhammad commented on src/api/entity/blog.ts
> +  @Column("integer")
yof ini entity blog untuk column author gimana?
isinya name sama userId harusnya.

2021-01-02 02:00 UTC, azhariemuhammad requested changes

2021-01-02 02:00 UTC, azhariemuhammad commented on src/api/schemas/blog.ts
> +  date: { type: "string" },
yof ini schema blog untuk column author gimana?
isinya name sama userId harusnya.

2021-01-28 14:23 UTC, yofriadi commented on src/api/schemas/blog.ts
> +  date: { type: "string" },
rie yang ini gimana yah, admin kan jadinya nanti nih jadi adminnya di hilangin sekarang

2021-01-28 14:31 UTC, ibnuimam approved these changes

2021-01-29 00:33 UTC, merged